# Usa Node.js como base
FROM node:20

# Establece el directorio de trabajo
WORKDIR /usr/src/app

# Copia los archivos necesarios
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el código del frontend
COPY . .

# Construye el frontend para producción
RUN npm run build

# Instala un servidor ligero para servir la app estática
RUN npm install -g serve

# Expone el puerto del frontend
EXPOSE 3000

# Comando para servir la app
CMD ["serve", "-s", "build", "-l", "3000"]
