# Usa una imagen base de Node.js
FROM node:20

# Establece el directorio de trabajo
WORKDIR /usr/src/app

# Copia los archivos necesarios
COPY package*.json ./

# Instala las dependencias, incluyendo nodemon
RUN npm install

# Instalar nodemon para visualizar cambios de manera instantanea
RUN npm install -g nodemon

# Copia el código fuente
COPY . .

# Exponer el puerto para el backend
EXPOSE 5010

# Comando por defecto
CMD ["npm", "run", "dev"]
